"""add last_login_notified_date

Revision ID: 8204db23c5be
Revises: edafc06f76ee
Create Date: 2026-05-20 15:24:32.670885

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '8204db23c5be'
down_revision = 'edafc06f76ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop push_tokens table if it exists
    try:
        op.drop_table('push_tokens')
    except Exception:
        # Table may not exist or foreign key already dropped
        pass
    
    with op.batch_alter_table('activity_entries', schema=None) as batch_op:
        batch_op.drop_column('steps')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login_notified_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('lock_until', sa.DateTime(), nullable=True))
        batch_op.drop_column('last_login_push_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login_push_date', sa.DATE(), nullable=True))
        batch_op.drop_column('lock_until')
        batch_op.drop_column('last_login_notified_date')

    with op.batch_alter_table('activity_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('steps', sa.Integer(), nullable=True))

    op.create_table('push_tokens',
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('push_tokens_ibfk_1')),
    sa.PrimaryKeyConstraint('token')
    )
    with op.batch_alter_table('push_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_push_tokens_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###
